version: '3.8'
services:
  app:
    build: .
    ports:
      - "8090:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: example
      DB_NAME: settingsdb
      REDIS_ADDR: redis:6379
      JWT_SECRET: example-secret

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: settingsdb
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    command: sh -c "docker-entrypoint.sh postgres && psql -U postgres -d settingsdb -f /docker-entrypoint-initdb.d/init.sql"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d settingsdb -t 3" ]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
